### ISSUE TITLE
Goblins animations, random attacks and attacking back behaviour

### ISSUE THREAD

**Issue by slard3** [MrCrayfish/GoblinTraders#13]
1) The goblins **Hurt** animations are broken
[videos](https://imgur.com/a/2pnNe4V)

2) Once the goblins spawn, they follow you. But if you ignore them, they hit you once and wait to do it again. Is that intended?

3) If you hit them, they hit you back sometimes, sometimes don't. Also they won't follow you anymore (the way the goblins follow you when they spawn, they do chase you to retaliate tho). Is any of this intended?

3) Also, there's the Issues link missing on the project on Curseforge

**Comment by MrCrayfish** [comment]
This is all intentional design. They are suppose to have an annoying personality, they want you to trade with them.
