### ISSUE TITLE
Server tick loop crash

### ISSUE THREAD

**Issue by Gaz492** [MrCrayfish/GoblinTraders#19]
Hi

Had my server crash multiple time due to what looks to be an issue with goblin traders.
You can find the crash report here https://pste.ch/ixojulabul.pl

The server is running Goblin traders 1.2.2

If you need any more information I'm happy to help.

**Comment by Piemaster651** [comment]
I'm getting the same issue. It's really frustrating I can't find any information about what's causing the crash. Did you figure anything out?

**Comment by EnterFor** [comment]
This is very confusing, it seems that the author does not intend to maintain this mod

**Comment by MrCrayfish** [comment]
Should be fixed in 67cbfdc361da2f6df1ff8b2e2ef60fb9b7d7683e
