### ISSUE TITLE
Conflict with Quark's Ancient Tomes

### ISSUE THREAD

**Issue by ChloeDawn** [MrCrayfish/GoblinTraders#25]
**Mod version:** 1.2.2

This mod's core mod conflicts with Quark's Ancient Tomes feature, allowing the player to combine max level books to obtain the ancient tome level, without needing an ancient tome as the secondary input.

**Example:** https://gfycat.com/ColorlessUnripeEgret

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/GoblinTraders/commit/c0cd67e8b0edef4be6082161bf8d69d9a8d69cc8
