### ISSUE TITLE
Suggestion: Add stat for amount of times traded with the Goblin Trader

### ISSUE THREAD

**Issue by Kutzeee** [MrCrayfish/GoblinTraders#26]
Just like how vanilla has a stat for Trades with Villagers, I think a Trades with Goblin Traders would be cool, could also be used for quest pack creators

**Comment by MrCrayfish** [comment]
Added in https://github.com/MrCrayfish/GoblinTraders/commit/11aa4774244fff2ea98013f75d2a73370e619c59
