### ISSUE TITLE
Newest goblin trader update cause fatal error with Apotheosis installed

### ISSUE THREAD

**Issue by Fogdile** [MrCrayfish/GoblinTraders#29]
Tried to boot up my datapack with the new goblin trader update and it crashes while loading and doesn't mention the cause. 
Found out the mod that causes it was Apotheosis. 
Attached the latest log, the error doesn't leave a crash log.

[latest.log](https://github.com/MrCrayfish/GoblinTraders/files/6152442/latest.log)

**Comment by MrCrayfish** [comment]
This should be fixed now in the latest patch!
