### ISSUE TITLE
Crash in mod list

### ISSUE THREAD

**Issue by magiczocker10** [MrCrayfish/GoblinTraders#3]
When selecting the Goblin Traders mod in the mod list, the game crashes.
![crash](https://user-images.githubusercontent.com/59317952/75090180-a6177d00-5560-11ea-9d59-617f76c7380e.png)

Forge version: 1.15.2-31.1.14
Mod version: 1.0.0

**Comment by MrCrayfish** [comment]
Is this a problem with the latest version?

**Comment by magiczocker10** [comment]
Thanks. The bug got fixed in v1.1.1.
