### ISSUE TITLE
Goblin Traders with Apotheosis are incompatible

### ISSUE THREAD

**Issue by celsiusqc** [MrCrayfish/GoblinTraders#31]
You mod does a change to the anvil and so does apotheosis. Apotheosis has a less invasive one. The creator of apotheosis says this is an issue on goblin traders side. Could you please fix
https://gist.github.com/celsiusqc/3f8bde8b36cf7c52cf41475e0ba95305

**Comment by MrCrayfish** [comment]
Literally already been fixed and patch released. I would disagree with invasive, I inject without replacing.
