### ISSUE TITLE
[Suggestion] Trading with goblin gives experience

### ISSUE THREAD

**Issue by MarioSMB** [MrCrayfish/GoblinTraders#32]
Much like trading with vanilla villagers and merchants, it would be nice if you received some experience for successful trades with the goblin trader.

**Comment by someaddons** [comment]
+1 could in onTrade() give the player experience equal to the merchant exp which is already configured

**Comment by MrCrayfish** [comment]
Added in https://github.com/MrCrayfish/GoblinTraders/commit/7c8eaea115aadfec24646e850032d74999eb1bd1 for 1.18 version
