### ISSUE TITLE
Conflict with Apotheosis mod

### ISSUE THREAD

**Issue by Art1xs** [MrCrayfish/GoblinTraders#34]
GoblinTraders mod creates a cap on enchantment levels. 
Imagine the cap for the enchantment "efficiency" is defaulted to 10 by Apotheosis. GoblinTraders will cause the max enchantment level to be one above the vanilla default (5).

**Comment by MrCrayfish** [comment]
Is this still an issue on the latest version? I rewrote the logic a while ago to respect level caps.

**Comment by Art1xs** [comment]
No, I'm pretty sure you fixed it! The mod works fine with me, right now at least.

**Comment by MrCrayfish** [comment]
Feel free to reopen if it's still an issue

**Comment by Art1xs** [comment]
Alright, Thank you!
