### ISSUE TITLE
[1.16.5] Spawner resets to pig spawner when not in Creative mode

### ISSUE THREAD

**Issue by MarioSMB** [MrCrayfish/GoblinTraders#35]
This is most notable on servers; placing creeper spawners purchased from the vein goblin miner while in Survival mode causes them to reset to the default pig spawner. In Creative mode, they correctly place as creeper spawners.

**Comment by MrCrayfish** [comment]
I've decided to remove the trade. It was experimental in the first place but I feel it doesn't fit with my vision of the mod.
