### ISSUE TITLE
[1.17.1] Will not load with Forge 1.17.1 - 37.0.59

### ISSUE THREAD

**Issue by ProsperCraft** [MrCrayfish/GoblinTraders#43]
Due to a mixin issue, I suspect because Forge includes mixins now.

https://gist.github.com/ProsperCraft/166245046964a14b83aefdd9b8819359

**Comment by JasperVanEsveld** [comment]
Yea it is a mixin issue
Seems like the refmap is not present in the build
It can't load `goblintraders.refmap.json`

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/GoblinTraders/commit/c78863f1767989fdf811f2f686f2d125bf1dd8fe
