### ISSUE TITLE
Feature request: Sound & aggressiveness config options

### ISSUE THREAD

**Issue by CyberTacoX** [MrCrayfish/GoblinTraders#47]
Hi! Could we please have some extra config options for:

1: How loud goblins are and how often they can grunt. Right now, I can't spend 10 minutes working on something without hearing a constant refrain of repeated grunting. I know I can make them show up less often; I just want them to be quieter while they're around.

2: How aggressively they seek you out. Right now, if they can't get to me, they'll get as close as they can and stand there grunting for *several minutes* like they want to talk to me about my car's extended warranty. I mean damn dude, if I didn't open the door for you, take the hint sooner and come back another time.

**Comment by AuroraHydroid** [comment]
I would like to add that in addition to toning down their aggressiveness, they seem determined to get in the way of my pick, sometimes throwing themselves onto the block I am breaking. Then they get smacked or dropped X blocks. Maybe reduce their suicidality?
