### ISSUE TITLE
Feature request: Ability to dismiss goblins

### ISSUE THREAD

**Issue by CyberTacoX** [MrCrayfish/GoblinTraders#48]
Hello! Could we please have some simple way to dismiss a goblin if we don't want to trade with them right now, aside from killing them, which I'd really rather not do?

**Comment by MrCrayfish** [comment]
Goblins will only stop following once you buy something. It's possible I can add a config option but that is essentially turning off their personality. Or you can just dig a hole and push them in it. Let me know.
