### ISSUE TITLE
Goblins disrupt minecarts

### ISSUE THREAD

**Issue by AuroraHydroid** [MrCrayfish/GoblinTraders#49]
Goblin Traders have spawned on my mine cart tracks, stopping hopper carts in their motion. It would be great if they avoided rail tracks like other mobs.

**Comment by MrCrayfish** [comment]
Thanks for the report. I've done some testing and conluded that everything is working correctly.
- Goblins will only spawn at safe positions and not on rails (exactly the same logic as Wandering Traders and other mobs when determining a safe position)
- Goblins will avoid rails. I use the same pathfinding system as every other mob in the game.

Having this said, it is still possible for any mob (not just the goblin) to walk on rails.
- Either they are pushed onto the rail
- They fall onto the rail (putting a block next to a rail can cause the pathfinding of the mob to walk onto the block and then fall onto the rail).

Feel free to test. Create a square with rails, place a block at a corner on the inside of the square (right next to the rail), spawn a zombie inside the square. Go into survival mode at the same corner you placed the block but on the outside of the square. You will now observe the zombie trying to follow you and it will use the placed block to fall onto the rail and escaping.

**Comment by MrCrayfish** [comment]
I turned up the spawn rate and all of them spawned on this small patch of dirt blocks
![image](https://user-images.githubusercontent.com/4958241/173199675-03f983de-fec8-4e48-90cf-504a1f85dd0d.png)
