### ISSUE TITLE
No Egg

### ISSUE THREAD

**Issue by Nordery** [MrCrayfish/GoblinTraders#5]
The goblin haven't egg for him for spawn a goblin
![2020-02-26_16 36 47](https://user-images.githubusercontent.com/61422642/75360139-b196db00-58b5-11ea-8328-4c3f6796d05c.png)
![2020-02-26_16 36 49](https://user-images.githubusercontent.com/61422642/75360154-b6f42580-58b5-11ea-8eef-aecc2b2a0829.png)

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/GoblinTraders/commit/3d071147c2e660dc7951ab79125c97a0b7c7f180
