### ISSUE TITLE
[1.18] goblin traders can't be configured to spawn below Y=0

### ISSUE THREAD

**Issue by esotericist** [MrCrayfish/GoblinTraders#52]
in 1.18, the world height by default goes from -64 to 319 in the overworld, and can potentially go much further negative (or further positive) in custom dimensions, in the vicinity of 2km in each direction from zero.

it'd be nice if the goblin configuration allowed a wider range reflecting the new java edition standards.

**Comment by MrCrayfish** [comment]
Fixed in latest version and default values have been changed.
