### ISSUE TITLE
[1.18.1] Incompatibility with Apotheosis

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MrCrayfish/GoblinTraders#54]
Hi, I believe I'm having a similar issue to #53 

Apotheosis allows enchantments to exceed their default max level, but your little anvil mixin prevents that from working at all - because you are imposing a hard cap w.r.t the default max of the enchantment.

Typically I would just point my redirector coremod at your classes calling `Enchantment#getMaxLevel` and be done with it, however, you are calling it from _within_ a mixin, so that's not a valid option.

https://github.com/MrCrayfish/GoblinTraders/blob/70381543cea4dbd1fa536e25f5eb106b5c307ddc/src/main/java/com/mrcrayfish/goblintraders/mixin/RepairContainerMixin.java#L46-L49

For Apotheosis to be compatible, you would need to place this call in another class, and call that other class from your mixin, (so I can point my coremod at your class, the same as I do with Quark [right here](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/src/main/resources/coremods/ench/ench_info_redirector.js#L56).

The other option would be to add a config value on your end that pack makers could flip off.  You might also be able to use the anvil events rather than a mixin, which would be easier to add configuration to.

**Comment by MrCrayfish** [comment]
I can definitely move the method to another class so it can be patched on your end. Does there need to be an exact signature so it can be targetted in your coremod or is it fine keeping it exactly the same (with the addition of a static modifer since it'd be moved)?

**Comment by Shadows-of-Fire** [comment]
There's no particular requirements, it just needs to be in a non-mixin class so I can point the coremod at it.
The coremod scans for any calls to replaced methods (in this case, `getMaxLevel`) and just redirects them to mine.

**Comment by didier-a17** [comment]
Same thing is happening in version 1.16.5

**Comment by MrCrayfish** [comment]
I saw your messages on Forge Discord, sorry I haven't got around to this. I am quite busy with lots of projects.

**Comment by MrCrayfish** [comment]
See `com.mrcrayfish.goblintraders.Hooks`
