### ISSUE TITLE
Bug: Goblin Traders incompatible with MC 1.18.2

### ISSUE THREAD

**Issue by iosgoodch** [MrCrayfish/GoblinTraders#57]
# Issue
Minecraft 1.18.2 crashes on launch when Goblin Traders mod is installed.

## Additional Information / Resources

Crash report:
[crash-2022-03-11_13.47.36-fml.txt](https://github.com/MrCrayfish/GoblinTraders/files/8235932/crash-2022-03-11_13.47.36-fml.txt)

**Comment by MrCrayfish** [comment]
Fixed by using the 1.18.2 version
