### ISSUE TITLE
Extending the range of supported entity types to IMerchant

### ISSUE THREAD

**Issue by LTCatt** [MrCrayfish/GoblinTraders#65]
https://github.com/AHilyard/MerchantMarkers/blob/1.16.5/src/main/java/com/anthonyhilyard/merchantmarkers/render/Markers.java

At line 150: `if (entity instanceof AbstractVillagerEntity)`

If you detect `IMerchant` instead of `AbstractVillagerEntity`, this mod can support merchants from more mods. For example, the Goblin Merchant, whose goblin entity does not inherit `AbstractVillagerEntity` because it does not have `Age`, but goblin implements `IMerchant`.

In fact, after I modified this code with mixin, the whole mod worked quite well...

**Comment by MrCrayfish** [comment]
Well I would suggest that to the author of that mod. Using a Mixin to patch another mod is not a good practice. I am all for adding support, don't get me wrong.

Edit: I believe you posted on the wrong repo based on the wording.

**Comment by LTCatt** [comment]
oh sorry it's my fault...
