### ISSUE TITLE
Goblin Trader still trades iron ore

### ISSUE THREAD

**Issue by AyunaMitsuki** [MrCrayfish/GoblinTraders#67]
So I have the recent version of better minecraft 1.16.5 and the goblin trader still trades iron ore but when I watch others play it recently, they have the raw iron trade. What do I do??

**Comment by MrCrayfish** [comment]
1.16.5 doesn't have raw iron. That's an item only available 1.18 or above. If better mc has installed a mod that backports the new caves and item, they will need to patch the trades with a datapack.
