### ISSUE TITLE
1.20.1 Goblin Traders not despawning? 

### ISSUE THREAD

**Issue by kezmodius** [MrCrayfish/GoblinTraders#81]
I am going in and out of creative mode for testing, so I don't know if that makes a difference.
I don't think the goblins are despawning. I'm playing Minecolonies and my colony is full of traders. The unnamed green dots on the map shot are all goblins! And they are just the ones in my vicinity rendering in. The other side of the colony has many also.
![2023-08-29_16 14 48](https://github.com/MrCrayfish/GoblinTraders/assets/120763436/34fb7f3b-e769-4fec-86e0-bf41ab994300)
![2023-08-29_16 16 23](https://github.com/MrCrayfish/GoblinTraders/assets/120763436/05ed3744-9cc1-4229-a154-a9d16dc8c0c4)

**Comment by MrCrayfish** [comment]
Should be fixed in newer versions
