### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by justsomebodynew** [MrCrayfish/GoblinTraders#83]
[crash-2023-09-04_17.46.05-client.txt](https://github.com/MrCrayfish/GoblinTraders/files/12516895/crash-2023-09-04_17.46.05-client.txt)

**Comment by MrCrayfish** [comment]
You have Iris installed on Forge. Also crash is unrelated to this mod.

**Comment by justsomebodynew** [comment]
When I remove the mod it doesn't crash.

**Comment by MrCrayfish** [comment]
I'd recommend reporting to the issue to the developers of Iris (Oculus on Forge) since the crash is the result of that mod, and no mention of Goblin Traders.
