### ISSUE TITLE
1.20.1 Goblin Traders despawning directly

### ISSUE THREAD

**Issue by UdoMorgenstern** [MrCrayfish/GoblinTraders#88]
goblintraders-forge-1.20.1-1.9.2
forge 47.1.3

Sidenotes: 
- no other mods installed to exclude "cross contamination"
- removed config file, to check if this might be a workaround

steps to reproduce:
- optional: create a new world
- grab any of the two goblin trader spawn eggs
- spawn one trader

outcome:
trader spawns in the world, but despawns in  a blink of an eye

expected:
trader should not despawn directly when placed into the world

**Comment by UdoMorgenstern** [comment]
probably fixed with SHA 908c7bc62e689976e0b7d41572054b8fdcbf6a79
"Fixed goblins despawning instantly with spawn egg"
but 1.9.3 not released on Curse Forge

**Comment by ItsYusei99** [comment]
how can i have this fix?

**Comment by SireOfTheQuags** [comment]
Issue's still here in the latest 1.20.1 version

**Comment by MrCrayfish** [comment]
Patch is now released
